# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Buienradar
                                 A QGIS plugin
 Een simpele plugin die realtime data van de buienradar api haalt
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-13
        copyright            : (C) 2019 by Peter Schols en Jeroen van der Zwam
        email                : jeroenvanderzwam@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Buienradar class from file Buienradar.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .buienradar_plugin import Buienradar
    return Buienradar(iface)
